[project]
name = "mwa_source_finder"
version = "0.1.3"
description = "Find sources in MWA observations."
authors = [
    { name = "Christopher Lee", email = "christopher.lee@icrar.org" },
    { name = "Nick Swainston" },
    { name = "Bradley Meyers" },
]
license = { file = "LICENSE" }
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">= 3.7"
dependencies = [
    "numpy >= 1.17.0",
    "matplotlib >= 3.5",
    "astropy",
    "pyyaml",
    "psrqpy >= 1.2.7",
    "mwa-hyperbeam",
    "tqdm",
    "ruff",
]

[project.scripts]
source-finder = "mwa_source_finder.cli:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py39"
include = [
    "pyproject.toml",
    "src/mwa_source_finder/*.py",
]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # flake8-bugbear
    "B",
    # isort
    "I",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"